### ISSUE TITLE
Splashes null when used in the blocklist editor in 8.7

### ISSUE THREAD

**Issue by Wolfkhan66** [bjarnef/color-pickr#1] opened 2020-09-28 15:15 UTC
Open a block that uses the color pickr.
Everything looks fine.
Close the block.
Open it again.
The splashes are now an array of [undefined, undefined etc] and the call const pickr = Pickr.create(options); throws an error.
This prevents any further changes to the selected colour being saved.

**Comment by bjarnef** [comment] 2020-10-03 19:03
@Wolfkhan66 I have checked this with Umbraco v8.7.0 and I am not able to reproduce this issue.

Could you tell a it more about your setup? Which browser are you using? Do you have any additional packages installed?

![rWSxh9RDTw](https://user-images.githubusercontent.com/2919859/94999978-69633800-05bd-11eb-920e-76515ae46b5f.gif)

**Comment by Wolfkhan66** [comment] 2020-10-12 10:58
@bjarnef Hi there, the issue I have described is with the predefined colours you can set on the data type labelled as 'Splashes'.
Without them there are no issues with changing and saving colours in blocks.

The issue only appears when you have setup a list of predefined colours. The first time you open the block all the predefined colours display fine for you to choose from and you can make and save changes. If you do nothing and close the block, then open it again, the predefined colours are undefined and prevents further changes to the colour to save.

**Comment by bjarnef** [comment] 2020-10-31 13:32
I really can't reproduce this issue even with predefined colors.
I don't see any console errors and the predefined colors are shown correct in the color picker.

![image](https://user-images.githubusercontent.com/2919859/97780461-1b722d80-1b85-11eb-8421-c40e2897a3ad.png)

When re-opening the block the previous save color is shown - also after saving the node.

![image](https://user-images.githubusercontent.com/2919859/97780416-d0581a80-1b84-11eb-85fb-3cf5f006a24b.png)

![FRbK94VaTF](https://user-images.githubusercontent.com/2919859/97781119-ab19db00-1b89-11eb-94dc-2b15a452f594.gif)

Could you please add some more details.
- Which browser and version do you use?
- Which Umbraco version?
- Do you have any other packages installed?
- Do you have any browser extensions installed?
- Have you tried this in incognito mode to ensure this isn't caused by any third party browser extensions?

**Comment by Wolfkhan66** [comment] 2020-11-02 10:43
Morning,
I have tried this in chrome (current version 85.0.4183.121), IE 11 and Edge( 86.0.622.58). 
I have also tried in incognito mode and had the same effect.
I have since upgraded from 8.7 to 8.8 then 8.9 and the issue is still present.
For other packages we currently have Our.Umbraco.Tables,  Our.Umbraco.GMaps and OpeningSoon installed.
We have no browser extensions.

Attached is a screenshot of the console error and how the picker looks when the error occurs.

In case it was something to do with the block setup I have recently moved the picker to the settings block but that made no difference.

The following is the swatches config we currently have:
[swatches.txt](https://github.com/bjarnef/color-pickr/files/5474357/swatches.txt)

Before: (first time opening the block)
![image](https://user-images.githubusercontent.com/11510721/97859376-6c566300-1cf8-11eb-82cc-bb15db1375f6.png)

After: (simply close the block without making changes, then open it again)
Console Error:
![image](https://user-images.githubusercontent.com/11510721/97859736-f0a8e600-1cf8-11eb-864a-63a510c3fffa.png)

Property Editor:
![image](https://user-images.githubusercontent.com/11510721/97859778-fbfc1180-1cf8-11eb-9cd4-0ff47bd93860.png)

**Comment by bjarnef** [comment] 2020-11-02 17:02
Do you use any of the mentioned packages or custom property editors on the blocks you are editing? Or do you have other custom property editors on the document type, where you have placed the block list editor?

I have tried added a datatype instance for each of these packages (Our.Umbraco.Tables, Our.Umbraco.GMaps and OpeningSoon) on the document type, where I have the block list editor, but I can't reproduce the error when opening and closing the block.

Are you able to reproduce the error in a clean install with e.g. default Starter Kit?

Do you use version latest v1.0.1? This version use Pickr v1.7.4 (you can see the version of this in `/App_Plugins/ColorPickr/pickr/pickr.min.js`)
https://our.umbraco.com/packages/backoffice-extensions/color-pickr

Have you also tried increasing the client dependency version number to ensure the latest version is bundled?
Example from OurUmbraco repository:
https://github.com/umbraco/OurUmbraco/blob/main/OurUmbraco.Site/config/ClientDependency.config#L13

**Comment by bjarnef** [comment] 2020-11-02 17:17
I have tried adding the same colors as well, which seems to work fine.

![dh4v1BXCcs](https://user-images.githubusercontent.com/2919859/97898025-97ac7280-1d37-11eb-9562-71263a099f0b.gif)

**Comment by Wolfkhan66** [comment] 2020-11-03 10:56
After trying everything I could think of I finally found the cause.
I removed every piece of javascript I could find that might have been loaded in. Changed every setting i could think of on the picker and on the blocks themselves. Increased the client dependency version. Removed all of the blocks and other property editors and updated every possible package. the issue was still there.

We do however have custom views for our blocks so we can have a live preview of changes. Once I turned off 'Live editing mode'  on the blocklist the issue stopped occurring on the colour picker.

Due to the custom view setup I'm not certain how easy recreating the issue is. I will run a few tests and report back

**Comment by bjarnef** [comment] 2020-11-03 13:49
@Wolfkhan66 great you find a bit more details of in which scenario the issue happens.
Let me know if you find more details or you can post the custom view and some details of the configuration of the block list editor + the element types it use.

**Closed as completed** 2021-02-26 12:14 UTC
